# Generated by Django 5.2.15 on 2026-06-25 08:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_book_author_book_commission_percent_book_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=80)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GatewayCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('telebirr', 'Telebirr')], max_length=20, unique=True)),
                ('public_key', models.CharField(blank=True, help_text='Publishable/client key (not secret).', max_length=500)),
                ('encrypted_secret', models.TextField(blank=True)),
                ('webhook_secret_encrypted', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gateway_credentials',
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('paypal_enabled', models.BooleanField(default=False)),
                ('telebirr_enabled', models.BooleanField(default=False)),
                ('manual_payment_enabled', models.BooleanField(default=True)),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('allow_author_override', models.BooleanField(default=True)),
                ('allow_book_override', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='AuthorCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_commission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'author_commissions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pen_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('payment_email', models.EmailField(blank=True, max_length=254)),
                ('telebirr_number', models.CharField(blank=True, max_length=40)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'author_profiles',
                'ordering': ['pen_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('telebirr', 'Telebirr'), ('bank_transfer', 'Bank transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on_review', 'On review'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('receipt_object_key', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.bank')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalog.book')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('author_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_entries', to='catalog.book')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'revenue_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='idx_audit_action')],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', '-created_at'], name='idx_txn_user_created'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', '-created_at'], name='idx_txn_status_created'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_reference', ''), _negated=True), fields=('payment_method', 'transaction_reference'), name='uniq_method_reference'),
        ),
        migrations.AddIndex(
            model_name='revenueledger',
            index=models.Index(fields=['author', '-created_at'], name='idx_ledger_author'),
        ),
        migrations.AddIndex(
            model_name='revenueledger',
            index=models.Index(fields=['book', '-created_at'], name='idx_ledger_book'),
        ),
    ]
