# Generated by Django 5.2.15 on 2026-06-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'reader'), ('author', 'author'), ('admin', 'admin')], default='reader', max_length=20),
        ),
    ]
