# Generated by Django 5.2.14 on 2026-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bookpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('psalms', 'Psalms & Mezmur'), ('marian', 'Marian'), ('liturgy', 'Liturgy'), ('synaxarium', 'Synaxarium'), ('saints', 'Saints & Gedl'), ('other', 'General')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='book',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='readers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
