# Generated by Django 5.2.14 on 2026-06-24 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_genre_book_is_premium_book_published_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('label_am', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['ordinal', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='other', max_length=64),
        ),
    ]
