# Generated by Django 5.2.15 on 2026-06-25 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-book override of the platform/author commission.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='book',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price; when set this is what buyers pay.', max_digits=12, null=True),
        ),
    ]
