# Generated by Django 5.2.14 on 2026-06-30 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_offlinedownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bible_name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='bible_short_name_am',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='bible_short_name_en',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='canonical_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_bible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='testament_type',
            field=models.CharField(blank=True, choices=[('old', 'Old Testament'), ('new', 'New Testament')], default='', max_length=3),
        ),
        migrations.CreateModel(
            name='BibleSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('ordinal', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('start_verse', models.PositiveSmallIntegerField(default=0)),
                ('end_verse', models.PositiveSmallIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_sections', to='catalog.book')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_sections', to='catalog.bookrevision')),
            ],
            options={
                'db_table': 'bible_sections',
                'ordering': ['revision', 'chapter', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text_plain', models.TextField(blank=True, default='')),
                ('text_normalized', models.TextField(blank=True, db_index=True, default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_verses', to='catalog.book')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_verses', to='catalog.bookrevision')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verses', to='catalog.biblesection')),
            ],
            options={
                'db_table': 'bible_verses',
                'ordering': ['revision', 'chapter', 'verse'],
            },
        ),
        migrations.AddIndex(
            model_name='biblesection',
            index=models.Index(fields=['book', 'chapter'], name='idx_bible_section_book_ch'),
        ),
        migrations.AddConstraint(
            model_name='biblesection',
            constraint=models.UniqueConstraint(fields=('revision', 'chapter', 'ordinal'), name='uniq_bible_section'),
        ),
        migrations.AddIndex(
            model_name='bibleverse',
            index=models.Index(fields=['book', 'chapter', 'verse'], name='idx_bible_verse_book_ch_v'),
        ),
        migrations.AddConstraint(
            model_name='bibleverse',
            constraint=models.UniqueConstraint(fields=('revision', 'chapter', 'verse'), name='uniq_bible_verse'),
        ),
    ]
