# Generated by Django 5.2.14 on 2026-06-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_bible_verse_trigram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibleverse',
            options={'ordering': ['revision', 'chapter', 'verse_seq']},
        ),
        migrations.RemoveConstraint(
            model_name='bibleverse',
            name='uniq_bible_verse',
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='verse_seq',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='bibleverse',
            constraint=models.UniqueConstraint(fields=('revision', 'chapter', 'verse_seq'), name='uniq_bible_verse_seq'),
        ),
    ]
