from django.urls import path

from apps.accounts.views import (
    ChangePasswordView,
    DeviceRegisterView,
    ForgotPasswordView,
    LoginView,
    LogoutView,
    MeView,
    RefreshView,
    RegisterView,
    ResetPasswordView,
)
from apps.catalog.admin_views import (
    AdminBookApproveReviewView,
    AdminBookCoverPresignView,
    AdminBookDraftValidationView,
    AdminBookDetailView,
    AdminBookImportDocxPreviewView,
    AdminBookImportDocxView,
    AdminBookPdfCompleteView,
    AdminBookPdfPresignView,
    AdminBookPublishView,
    AdminBookRejectReviewView,
    AdminBookReviewNotesView,
    AdminBooksRootView,
    AdminBookSubmitReviewView,
    AdminBookUnpublishView,
    AdminBookWithdrawReviewView,
    AdminRevisionCompleteView,
    AdminRevisionCreateView,
)
from apps.catalog.admin_bible_views import (
    AdminBibleChaptersView,
    AdminBibleChapterView,
)
from apps.catalog.bible_views import (
    BibleBookListView,
    BibleChapterListView,
    BibleChapterView,
    BibleReferenceView,
    BibleSearchView,
)
from apps.catalog.views import (
    BookChapterListView,
    BookContentView,
    BookDetailView,
    BookDownloadView,
    BookCoverView,
    BookLicenseView,
    BookListView,
    BookPdfView,
    BookSearchView,
    GenreListView,
    SyncCatalogView,
    TagListView,
)
from apps.legal.views import LegalAcceptanceView, LegalDocumentListView
from apps.payments.admin_views import (
    AdminApproveAuthorApplicationView,
    AdminApproveTransactionView,
    AdminAuthorApplicationDetailView,
    AdminAuthorApplicationsView,
    AdminAuthorCommissionDetailView,
    AdminAuthorCommissionsView,
    AdminBankDetailView,
    AdminBanksView,
    AdminGatewayCredentialDetailView,
    AdminGatewayCredentialsView,
    AdminPaymentDashboardView,
    AdminPlatformSettingsView,
    AdminRejectAuthorApplicationView,
    AdminRejectTransactionView,
    AdminTransactionDetailView,
    AdminTransactionsView,
)
from apps.payments.views import (
    AuthorApplicationPhotoPresignView,
    AuthorApplicationView,
    AuthorDashboardView,
    AuthorProfileView,
    BankListView,
    PaymentMethodsView,
    EntitlementsView,
    PaymentTransactionDetailView,
    PaymentTransactionsView,
    PayPalWebhookView,
    ReceiptFileView,
    StripeWebhookView,
    SubmitReceiptView,
    TelebirrWebhookView,
)
from apps.study.views import (
    BookReviewDetailView,
    BookReviewsView,
    DailyReadingPlanDetailView,
    DailyReadingPlansView,
    FavouriteDetailView,
    FavouritesView,
    NotificationDetailView,
    NotificationsView,
    ReminderPreferenceView,
    StudyBookmarkDetailView,
    StudyBookmarksView,
    StudyFolderDetailView,
    StudyFolderEntriesView,
    StudyFolderEntryDetailView,
    StudyFoldersView,
    StudyHighlightDetailView,
    StudyHighlightsView,
    StudyReadingProgressView,
    StudyNoteDetailView,
    StudyNotesView,
    ReaderEventsView,
    StudyRemindersView,
)

urlpatterns = [
    path("auth/register", RegisterView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("auth/refresh", RefreshView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("auth/forgot-password", ForgotPasswordView.as_view()),
    path("auth/reset-password", ResetPasswordView.as_view()),
    path("auth/change-password", ChangePasswordView.as_view()),
    path("me", MeView.as_view()),
    path("devices/register", DeviceRegisterView.as_view()),
    path("legal/documents", LegalDocumentListView.as_view()),
    path("legal/acceptances", LegalAcceptanceView.as_view()),
    path("genres", GenreListView.as_view()),
    path("tags", TagListView.as_view()),
    path("books", BookListView.as_view()),
    path("sync/catalog", SyncCatalogView.as_view()),
    path("books/<uuid:book_id>", BookDetailView.as_view()),
    path("books/<uuid:book_id>/cover", BookCoverView.as_view()),
    path("books/<uuid:book_id>/download", BookDownloadView.as_view()),
    path("books/<uuid:book_id>/license", BookLicenseView.as_view()),
    path("books/<uuid:book_id>/chapters", BookChapterListView.as_view()),
    path("books/<uuid:book_id>/content", BookContentView.as_view()),
    path("books/<uuid:book_id>/pdf", BookPdfView.as_view()),
    path("books/<uuid:book_id>/search", BookSearchView.as_view()),
    # --- Bible (verse-addressable open content) ---
    path("bible/books", BibleBookListView.as_view()),
    path("bible/search", BibleSearchView.as_view()),
    path("bible/reference", BibleReferenceView.as_view()),
    path("bible/books/<uuid:book_id>/chapters", BibleChapterListView.as_view()),
    path("bible/books/<uuid:book_id>/chapters/<int:chapter>", BibleChapterView.as_view()),
    path(
        "admin/bible/books/<uuid:book_id>/chapters",
        AdminBibleChaptersView.as_view(),
    ),
    path(
        "admin/bible/books/<uuid:book_id>/chapters/<int:chapter>",
        AdminBibleChapterView.as_view(),
    ),
    path("admin/books", AdminBooksRootView.as_view()),
    path("admin/books/import-docx", AdminBookImportDocxView.as_view()),
    path("admin/books/import-docx/preview", AdminBookImportDocxPreviewView.as_view()),
    path("admin/books/<uuid:book_id>", AdminBookDetailView.as_view()),
    path("admin/books/<uuid:book_id>/validate-draft", AdminBookDraftValidationView.as_view()),
    path("admin/books/<uuid:book_id>/cover/presign", AdminBookCoverPresignView.as_view()),
    path("admin/books/<uuid:book_id>/pdf/presign", AdminBookPdfPresignView.as_view()),
    path("admin/books/<uuid:book_id>/pdf/complete", AdminBookPdfCompleteView.as_view()),
    path("admin/books/<uuid:book_id>/publish", AdminBookPublishView.as_view()),
    path("admin/books/<uuid:book_id>/unpublish", AdminBookUnpublishView.as_view()),
    path("admin/books/<uuid:book_id>/submit-review", AdminBookSubmitReviewView.as_view()),
    path("admin/books/<uuid:book_id>/withdraw-review", AdminBookWithdrawReviewView.as_view()),
    path("admin/books/<uuid:book_id>/review/approve", AdminBookApproveReviewView.as_view()),
    path("admin/books/<uuid:book_id>/review/reject", AdminBookRejectReviewView.as_view()),
    path("admin/books/<uuid:book_id>/review-notes", AdminBookReviewNotesView.as_view()),
    path("admin/books/<uuid:book_id>/revisions", AdminRevisionCreateView.as_view()),
    path(
        "admin/books/<uuid:book_id>/revisions/<uuid:revision_id>/complete",
        AdminRevisionCompleteView.as_view(),
    ),
    path("study/bookmarks", StudyBookmarksView.as_view()),
    path("study/bookmarks/<uuid:item_id>", StudyBookmarkDetailView.as_view()),
    path("study/highlights", StudyHighlightsView.as_view()),
    path("study/highlights/<uuid:item_id>", StudyHighlightDetailView.as_view()),
    path("study/notes", StudyNotesView.as_view()),
    path("study/notes/<uuid:item_id>", StudyNoteDetailView.as_view()),
    path("study/folders", StudyFoldersView.as_view()),
    path("study/folders/<uuid:item_id>", StudyFolderDetailView.as_view()),
    path("study/folder-entries", StudyFolderEntriesView.as_view()),
    path("study/folder-entries/<uuid:item_id>", StudyFolderEntryDetailView.as_view()),
    path("study/plans", DailyReadingPlansView.as_view()),
    path("study/plans/<uuid:item_id>", DailyReadingPlanDetailView.as_view()),
    path("study/reminder-preference", ReminderPreferenceView.as_view()),
    path("study/reminders", StudyRemindersView.as_view()),
    path("study/progress/<uuid:book_id>", StudyReadingProgressView.as_view()),
    path("study/events", ReaderEventsView.as_view()),
    path("study/favourites", FavouritesView.as_view()),
    path("study/favourites/<uuid:book_id>", FavouriteDetailView.as_view()),
    path("study/reviews", BookReviewsView.as_view()),
    path("study/reviews/<uuid:book_id>", BookReviewDetailView.as_view()),
    path("study/notifications", NotificationsView.as_view()),
    path("study/notifications/<uuid:item_id>", NotificationDetailView.as_view()),
    # --- Payments (buyer + author) ---
    path("payments/methods", PaymentMethodsView.as_view()),
    path("payments/entitlements", EntitlementsView.as_view()),
    path("payments/banks", BankListView.as_view()),
    path("payments/transactions", PaymentTransactionsView.as_view()),
    path("payments/transactions/<uuid:transaction_id>", PaymentTransactionDetailView.as_view()),
    path("payments/transactions/<uuid:transaction_id>/receipt", SubmitReceiptView.as_view()),
    path("payments/transactions/<uuid:transaction_id>/receipt-file", ReceiptFileView.as_view()),
    path("payments/webhooks/stripe", StripeWebhookView.as_view()),
    path("payments/webhooks/paypal", PayPalWebhookView.as_view()),
    path("payments/webhooks/telebirr", TelebirrWebhookView.as_view()),
    path("author/dashboard", AuthorDashboardView.as_view()),
    path("author/profile", AuthorProfileView.as_view()),
    # --- Author application (reader -> author request) ---
    path("author/application", AuthorApplicationView.as_view()),
    path("author/application/photo/presign", AuthorApplicationPhotoPresignView.as_view()),
    # --- Payments admin ---
    path("admin/payments/dashboard", AdminPaymentDashboardView.as_view()),
    path("admin/payments/transactions", AdminTransactionsView.as_view()),
    path("admin/payments/transactions/<uuid:transaction_id>", AdminTransactionDetailView.as_view()),
    path("admin/payments/transactions/<uuid:transaction_id>/approve", AdminApproveTransactionView.as_view()),
    path("admin/payments/transactions/<uuid:transaction_id>/reject", AdminRejectTransactionView.as_view()),
    path("admin/payments/banks", AdminBanksView.as_view()),
    path("admin/payments/banks/<uuid:bank_id>", AdminBankDetailView.as_view()),
    path("admin/payments/settings", AdminPlatformSettingsView.as_view()),
    path("admin/payments/credentials", AdminGatewayCredentialsView.as_view()),
    path("admin/payments/credentials/<str:provider>", AdminGatewayCredentialDetailView.as_view()),
    path("admin/payments/author-commissions", AdminAuthorCommissionsView.as_view()),
    path("admin/payments/author-commissions/<uuid:commission_id>", AdminAuthorCommissionDetailView.as_view()),
    # --- Author applications admin ---
    path("admin/author-applications", AdminAuthorApplicationsView.as_view()),
    path("admin/author-applications/<uuid:application_id>", AdminAuthorApplicationDetailView.as_view()),
    path("admin/author-applications/<uuid:application_id>/approve", AdminApproveAuthorApplicationView.as_view()),
    path("admin/author-applications/<uuid:application_id>/reject", AdminRejectAuthorApplicationView.as_view()),
]
