from django.urls import path

from apps.accounts.views import (
    ForgotPasswordView,
    LoginView,
    LogoutView,
    MeView,
    RefreshView,
    RegisterView,
    ResetPasswordView,
)
from apps.catalog.admin_views import (
    AdminBookCoverPresignView,
    AdminBookDraftValidationView,
    AdminBookDetailView,
    AdminBookPublishView,
    AdminBooksRootView,
    AdminBookUnpublishView,
    AdminRevisionCompleteView,
    AdminRevisionCreateView,
)
from apps.catalog.views import (
    BookChapterListView,
    BookContentView,
    BookDetailView,
    BookDownloadView,
    BookCoverView,
    BookListView,
    BookSearchView,
    GenreListView,
    SyncCatalogView,
    TagListView,
)
from apps.legal.views import LegalAcceptanceView, LegalDocumentListView
from apps.payments.admin_views import (
    AdminApproveTransactionView,
    AdminAuthorCommissionDetailView,
    AdminAuthorCommissionsView,
    AdminBankDetailView,
    AdminBanksView,
    AdminGatewayCredentialDetailView,
    AdminGatewayCredentialsView,
    AdminPaymentDashboardView,
    AdminPlatformSettingsView,
    AdminRejectTransactionView,
    AdminTransactionDetailView,
    AdminTransactionsView,
)
from apps.payments.views import (
    AuthorDashboardView,
    AuthorProfileView,
    BankListView,
    PaymentMethodsView,
    EntitlementsView,
    PaymentTransactionDetailView,
    PaymentTransactionsView,
    PayPalWebhookView,
    ReceiptFileView,
    StripeWebhookView,
    SubmitReceiptView,
    TelebirrWebhookView,
)
from apps.study.views import (
    BookReviewDetailView,
    BookReviewsView,
    DailyReadingPlanDetailView,
    DailyReadingPlansView,
    FavouriteDetailView,
    FavouritesView,
    NotificationDetailView,
    NotificationsView,
    ReminderPreferenceView,
    StudyBookmarkDetailView,
    StudyBookmarksView,
    StudyFolderDetailView,
    StudyFolderEntriesView,
    StudyFolderEntryDetailView,
    StudyFoldersView,
    StudyHighlightDetailView,
    StudyHighlightsView,
    StudyReadingProgressView,
    StudyNoteDetailView,
    StudyNotesView,
    ReaderEventsView,
    StudyRemindersView,
)

urlpatterns = [
    path("auth/register", RegisterView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("auth/refresh", RefreshView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("auth/forgot-password", ForgotPasswordView.as_view()),
    path("auth/reset-password", ResetPasswordView.as_view()),
    path("me", MeView.as_view()),
    path("legal/documents", LegalDocumentListView.as_view()),
    path("legal/acceptances", LegalAcceptanceView.as_view()),
    path("genres", GenreListView.as_view()),
    path("tags", TagListView.as_view()),
    path("books", BookListView.as_view()),
    path("sync/catalog", SyncCatalogView.as_view()),
    path("books/<uuid:book_id>", BookDetailView.as_view()),
    path("books/<uuid:book_id>/cover", BookCoverView.as_view()),
    path("books/<uuid:book_id>/download", BookDownloadView.as_view()),
    path("books/<uuid:book_id>/chapters", BookChapterListView.as_view()),
    path("books/<uuid:book_id>/content", BookContentView.as_view()),
    path("books/<uuid:book_id>/search", BookSearchView.as_view()),
    path("admin/books", AdminBooksRootView.as_view()),
    path("admin/books/<uuid:book_id>", AdminBookDetailView.as_view()),
    path("admin/books/<uuid:book_id>/validate-draft", AdminBookDraftValidationView.as_view()),
    path("admin/books/<uuid:book_id>/cover/presign", AdminBookCoverPresignView.as_view()),
    path("admin/books/<uuid:book_id>/publish", AdminBookPublishView.as_view()),
    path("admin/books/<uuid:book_id>/unpublish", AdminBookUnpublishView.as_view()),
    path("admin/books/<uuid:book_id>/revisions", AdminRevisionCreateView.as_view()),
    path(
        "admin/books/<uuid:book_id>/revisions/<uuid:revision_id>/complete",
        AdminRevisionCompleteView.as_view(),
    ),
    path("study/bookmarks", StudyBookmarksView.as_view()),
    path("study/bookmarks/<uuid:item_id>", StudyBookmarkDetailView.as_view()),
    path("study/highlights", StudyHighlightsView.as_view()),
    path("study/highlights/<uuid:item_id>", StudyHighlightDetailView.as_view()),
    path("study/notes", StudyNotesView.as_view()),
    path("study/notes/<uuid:item_id>", StudyNoteDetailView.as_view()),
    path("study/folders", StudyFoldersView.as_view()),
    path("study/folders/<uuid:item_id>", StudyFolderDetailView.as_view()),
    path("study/folder-entries", StudyFolderEntriesView.as_view()),
    path("study/folder-entries/<uuid:item_id>", StudyFolderEntryDetailView.as_view()),
    path("study/plans", DailyReadingPlansView.as_view()),
    path("study/plans/<uuid:item_id>", DailyReadingPlanDetailView.as_view()),
    path("study/reminder-preference", ReminderPreferenceView.as_view()),
    path("study/reminders", StudyRemindersView.as_view()),
    path("study/progress/<uuid:book_id>", StudyReadingProgressView.as_view()),
    path("study/events", ReaderEventsView.as_view()),
    path("study/favourites", FavouritesView.as_view()),
    path("study/favourites/<uuid:book_id>", FavouriteDetailView.as_view()),
    path("study/reviews", BookReviewsView.as_view()),
    path("study/reviews/<uuid:book_id>", BookReviewDetailView.as_view()),
    path("study/notifications", NotificationsView.as_view()),
    path("study/notifications/<uuid:item_id>", NotificationDetailView.as_view()),
    # --- Payments (buyer + author) ---
    path("payments/methods", PaymentMethodsView.as_view()),
    path("payments/entitlements", EntitlementsView.as_view()),
    path("payments/banks", BankListView.as_view()),
    path("payments/transactions", PaymentTransactionsView.as_view()),
    path("payments/transactions/<uuid:transaction_id>", PaymentTransactionDetailView.as_view()),
    path("payments/transactions/<uuid:transaction_id>/receipt", SubmitReceiptView.as_view()),
    path("payments/transactions/<uuid:transaction_id>/receipt-file", ReceiptFileView.as_view()),
    path("payments/webhooks/stripe", StripeWebhookView.as_view()),
    path("payments/webhooks/paypal", PayPalWebhookView.as_view()),
    path("payments/webhooks/telebirr", TelebirrWebhookView.as_view()),
    path("author/dashboard", AuthorDashboardView.as_view()),
    path("author/profile", AuthorProfileView.as_view()),
    # --- Payments admin ---
    path("admin/payments/dashboard", AdminPaymentDashboardView.as_view()),
    path("admin/payments/transactions", AdminTransactionsView.as_view()),
    path("admin/payments/transactions/<uuid:transaction_id>", AdminTransactionDetailView.as_view()),
    path("admin/payments/transactions/<uuid:transaction_id>/approve", AdminApproveTransactionView.as_view()),
    path("admin/payments/transactions/<uuid:transaction_id>/reject", AdminRejectTransactionView.as_view()),
    path("admin/payments/banks", AdminBanksView.as_view()),
    path("admin/payments/banks/<uuid:bank_id>", AdminBankDetailView.as_view()),
    path("admin/payments/settings", AdminPlatformSettingsView.as_view()),
    path("admin/payments/credentials", AdminGatewayCredentialsView.as_view()),
    path("admin/payments/credentials/<str:provider>", AdminGatewayCredentialDetailView.as_view()),
    path("admin/payments/author-commissions", AdminAuthorCommissionsView.as_view()),
    path("admin/payments/author-commissions/<uuid:commission_id>", AdminAuthorCommissionDetailView.as_view()),
]
